import GithubSlugger from "github-slugger";

export type Heading = {
  id: string;
  text: string;
  level: 2 | 3;
};

const HEADING_RE = /^(#{2,3})\s+(.+?)\s*#*\s*$/;

/**
 * Extract h2/h3 headings from a markdown source string.
 *
 * - Skips fenced code blocks (``` or ~~~).
 * - Ignores h1 and h4+.
 * - Slug ids are generated by `github-slugger`, matching the algorithm
 *   used by `rehype-slug` in the MDX pipeline. This keeps the TOC
 *   anchors in sync with the rendered heading ids.
 * - Pure function: no IO, no side effects.
 */
export function extractHeadings(source: string): Heading[] {
  const lines = source.split(/\r?\n/);
  const headings: Heading[] = [];
  const slugger = new GithubSlugger();
  let fenceMarker: string | null = null;

  for (const line of lines) {
    if (fenceMarker !== null) {
      // inside a fenced code block — wait for closing fence
      const trimmed = line.trim();
      if (trimmed.startsWith(fenceMarker)) {
        fenceMarker = null;
      }
      continue;
    }

    const trimmed = line.trimStart();
    if (trimmed.startsWith("```") || trimmed.startsWith("~~~")) {
      fenceMarker = trimmed.slice(0, 3);
      continue;
    }

    const match = HEADING_RE.exec(line);
    if (!match) continue;

    const hashes = match[1]!;
    const text = match[2]!.trim();
    const level = (hashes.length === 2 ? 2 : 3) as 2 | 3;

    const id = slugger.slug(text);

    headings.push({ id, text, level });
  }

  return headings;
}
